//! Deckbuilder data: card-pool entries + preset decks.
//!
//! Two FFI-facing shapes:
//!
//! - [`CardPoolEntry`] — one entry per card the deckbuilder can offer
//!   (filtered via [`playable_pool`]). Holds the readable fields the
//!   browser UI needs: id, name, kind, cost text, colors, symbols,
//!   subtypes, ability lines, creature stats, spell timing.
//! - [`PresetDeck`] — one entry per shipped curated deck. Today: a
//!   Blue Starter and a Red Starter, each a flat `Vec<String>` of
//!   card IDs (50 entries with repetition) — the same shape
//!   `tsot_start_game`'s `deck_a_ids` / `deck_b_ids` consume.
//!
//! The gauntlet-variant decks (Ra/Rb/Hu/Go/Uu/Pr/Gg) used to ship as
//! presets here; they live on inside `sim::variants` / `sim::fitness`
//! for the EA's fitness-evaluation gauntlet, but no longer surface in
//! the preset dropdown.

use crate::card::Card;
use crate::sim::snapshot::format_cost;

/// One card available in the deckbuilder. Shape mirrors what the JS
/// UI reads from in-game `CardView` snapshots so the renderer can be
/// shared.
#[derive(Debug, Clone, serde::Serialize)]
pub struct CardPoolEntry {
    pub id: String,
    pub name: String,
    /// `CardType` serialized as its variant name: `"Creature"` /
    /// `"Spell"` / `"Artifact"` / `"Environment"` / `"Mutation"` /
    /// `"Unspecified"`.
    pub kind: crate::card::CardType,
    /// Printed cost as a readable string: `"2H"`, `"1H+1G"`, `"0"`.
    /// Same format the in-game CardView uses, generated by
    /// [`crate::sim::snapshot::format_cost`].
    pub cost_text: String,
    pub colors: Vec<String>,
    pub symbols: Vec<String>,
    pub subtypes: Vec<String>,
    /// Creatures only. `None` for non-creature cards. Stored as
    /// `Stats.x` on the card — printed power, pre-modifiers.
    pub power: Option<f32>,
    /// Creatures only. `None` for non-creature cards. Stored as
    /// `Stats.y` on the card — printed toughness, pre-modifiers.
    pub toughness: Option<f32>,
    /// Spells only — `"Instant"` or `"Sorcery"`. `None` otherwise.
    pub timing: Option<crate::card::Timing>,
    /// Rendered ability lines (the same array `assets/play.html`
    /// shows in the card body).
    pub abilities: Vec<String>,
}

/// One shipped preset deck.
#[derive(Debug, Clone, serde::Serialize)]
pub struct PresetDeck {
    /// Stable identifier: `"starter"`, `"gauntlet-ra"`, … —
    /// used as the key in the JS preset dropdown.
    pub id: String,
    /// Display name in the preset dropdown.
    pub name: String,
    /// Flat array of card IDs with repetition; length = 50 for every
    /// shipped preset. Same shape as `tsot_start_game`'s `deck_a_ids`.
    pub cards: Vec<String>,
}

/// The current starter deck — same composition that
/// `assets/play.html` boots the deckbuilder into. Composition after
/// the Symbol-design slice + the user's blue-shell follow-up:
///    2 blue-monkey + 11 clear-blue + 10 blue-symbol (2× each glyph)
///   + 2 blue-jewel + 1 companion-bird + 2 counterspell + 1 surge
///   + 1 unblockable-human + 2 reef-phantom + 1 stream-of-thought
///   + 2 klotho + 1 beguile + 1 avatar-of-greed + 1 field-notes
///   + 2 jellyfish + 2 mesopelagic-fish + 2 mist-bat
///   + 2 wandering-wizard + 1 frost-cat + 1 glass-damselfly
///   + 2 blue-scientist  =  50.
pub const STARTER_DECK_IDS: &[&str] = &[
    "blue-monkey", "blue-monkey",
    "clear-blue", "clear-blue", "clear-blue", "clear-blue", "clear-blue",
    "clear-blue", "clear-blue", "clear-blue", "clear-blue", "clear-blue",
    "clear-blue",
    "blue-ax-symbol", "blue-ax-symbol",
    "blue-ix-symbol", "blue-ix-symbol",
    "blue-am-symbol", "blue-am-symbol",
    "blue-pulse-symbol", "blue-pulse-symbol",
    "blue-sem-symbol", "blue-sem-symbol",
    "blue-jewel", "blue-jewel",
    "companion-bird",
    "counterspell", "counterspell",
    "surge",
    "unblockable-human",
    "reef-phantom", "reef-phantom",
    "stream-of-thought",
    "KLOTHO", "KLOTHO",
    "beguile",
    "avatar-of-greed",
    "field-notes",
    "jellyfish", "jellyfish",
    "mesopelagic-fish", "mesopelagic-fish",
    "mist-bat", "mist-bat",
    "wandering-wizard", "wandering-wizard",
    "frost-cat",
    "glass-damselfly",
    "blue-scientist", "blue-scientist",
];

/// Lua-yield test deck (2026-06-10). Built to exercise the resolved
/// LIMITATIONS.md ## lua bug end-to-end: every cast of a yielding
/// card (read-the-embers / fireball / portable-bolt / signal-goblin
/// on_attack) should now surface a `HumanPrompt::ChooseCard` and
/// resume on user answer instead of erroring silently.
///
/// Composition: a Red base for cost payments, then high counts of the
/// three on_play yielders + signal-goblin (whose on_attack also calls
/// `game.choose_card`). 50 cards.
pub const YIELD_TEST_DECK_IDS: &[&str] = &[
    // Hand-source bedrock — `clear-red` is the cheap pitch for the
    // 1H components on every red spell.
    "clear-red", "clear-red", "clear-red", "clear-red", "clear-red",
    "clear-red", "clear-red", "clear-red", "clear-red", "clear-red",
    "clear-red", "clear-red", "clear-red",
    // Red symbol cards — graveyard fodder for X-cost graveyard slots
    // (read-the-embers needs them).
    "red-ax-symbol", "red-ax-symbol",
    "red-ix-symbol", "red-ix-symbol",
    "red-am-symbol", "red-am-symbol",
    "red-pulse-symbol", "red-pulse-symbol",
    "red-sem-symbol", "red-sem-symbol",
    "red-jewel", "red-jewel",
    // The yield-test triggers — extra copies so they show up early.
    "read-the-embers", "read-the-embers", "read-the-embers",
    "fireball", "fireball", "fireball",
    "portable-bolt", "portable-bolt", "portable-bolt",
    // signal-goblin's on_attack ALSO calls `game.choose_card` — extra
    // test coverage of the combat-side path.
    "signal-goblin", "signal-goblin",
    // Creatures to attack with (gives signal-goblin a stage), plus
    // pool members so the yielders have targets.
    "ember-bat", "ember-bat", "ember-bat", "ember-bat",
    "cinder-wurm", "cinder-wurm", "cinder-wurm",
    "goblin-warchief", "goblin-warchief",
    "sparkle", "sparkle",
    "haste-human", "haste-human", "haste-human",
];

/// Red counterpart of [`STARTER_DECK_IDS`]. Direct color swaps for
/// every monkey / clear / symbol / jewel; the remaining slots are
/// filled with user-specified red cards.
pub const RED_STARTER_DECK_IDS: &[&str] = &[
    "red-monkey", "red-monkey",
    "clear-red", "clear-red", "clear-red", "clear-red", "clear-red",
    "clear-red", "clear-red", "clear-red", "clear-red", "clear-red",
    "clear-red",
    "red-ax-symbol", "red-ax-symbol",
    "red-ix-symbol", "red-ix-symbol",
    "red-am-symbol", "red-am-symbol",
    "red-pulse-symbol", "red-pulse-symbol",
    "red-sem-symbol", "red-sem-symbol",
    "red-jewel", "red-jewel",
    "goblin-berserker", "goblin-berserker",
    "goblin-warchief", "goblin-warchief",
    "signal-goblin", "signal-goblin",
    "portable-bolt", "portable-bolt",
    "fireball", "fireball",
    "red-devil",
    "tantrum-imp",
    "FST",
    "ember-bat", "ember-bat",
    "ember-dragon", "ember-dragon",
    "read-the-embers", "read-the-embers",
    "sparkle", "sparkle",
    "haste-human", "haste-human",
    "cinder-wurm", "cinder-wurm",
];

/// Build `CardPoolEntry` rows from a playable-pool slice.
pub fn build_card_pool_entries(pool: &[Card]) -> Vec<CardPoolEntry> {
    pool.iter().map(card_to_entry).collect()
}

fn card_to_entry(card: &Card) -> CardPoolEntry {
    let (power, toughness) = match card.stats {
        Some(s) => (Some(s.x), Some(s.y)),
        None => (None, None),
    };
    CardPoolEntry {
        id: card.id.clone(),
        name: card.name.clone(),
        kind: card.kind,
        cost_text: format_cost(&card.cost),
        colors: card.colors.clone(),
        symbols: card.symbols.clone(),
        subtypes: card.subtypes.clone(),
        power,
        toughness,
        timing: card.timing,
        abilities: card.abilities.clone(),
    }
}

/// Build the shipped presets. Order is fixed so the JS preset dropdown
/// is stable across reloads.
pub fn build_preset_decks(_playable: &[Card]) -> Vec<PresetDeck> {
    // The first entry whose `id == "starter"` is what the deckbuilder
    // auto-loads on page boot (see assets/play.html bootstrap).
    // Per user request 2026-06-09: red is the default starter.
    // Yield Test added 2026-06-10 to exercise the resolved Lua-yield
    // bug (LIMITATIONS.md ## lua) end-to-end.
    vec![
        PresetDeck {
            id: "starter".to_string(),
            name: "Red Starter".to_string(),
            cards: RED_STARTER_DECK_IDS.iter().map(|s| s.to_string()).collect(),
        },
        PresetDeck {
            id: "starter-blue".to_string(),
            name: "Blue Starter".to_string(),
            cards: STARTER_DECK_IDS.iter().map(|s| s.to_string()).collect(),
        },
        PresetDeck {
            id: "yield-test".to_string(),
            name: "Yield Test (Red)".to_string(),
            cards: YIELD_TEST_DECK_IDS.iter().map(|s| s.to_string()).collect(),
        },
        // Chaos-engineering deck: 50× Faal. Each Faal carries six
        // tap-activated abilities that each trigger a distinct
        // sacred-error pipeline branch. Use this preset to verify
        // ERROR.md items end-to-end in the dev tool — tap an
        // ability, observe the typed-Error overlay shape. See
        // `cards/faal.lua` for the failure-mode map.
        PresetDeck {
            id: "faal-chaos".to_string(),
            name: "Faal Test (chaos eng.)".to_string(),
            cards: std::iter::repeat_n("faal".to_string(), 50).collect(),
        },
        // Slice #4 verifier: 50× Golden Egg. Golden Egg's activated
        // ability is "T, exile this: draw a card" — the only corpus
        // card today whose activated cost uses CostSource::SelfExile.
        // Cast one to board, tap+exile-self to draw. Verifies the
        // post-effect SelfExile move from `play/activate.rs` runs and
        // the source actually lands in EXILE.
        //
        // Self-sustaining loop: hand starts with 5 eggs; U.10 end-of-
        // turn discard down to 6 puts a 6th-drawn egg in graveyard on
        // turn 1, enabling the 1gy cost from turn 2 onward. Each cast
        // pays 1gy + 4mill — net +3 eggs to graveyard per cast. Each
        // T-activation draws a fresh egg from deck. The loop runs
        // until the deck runs out (deck-out loss). Pure non-legal
        // chaos-eng deck, same pattern as faal-chaos.
        PresetDeck {
            id: "golden-egg-test".to_string(),
            name: "Golden Egg Test (slice #4 SELF activated)".to_string(),
            cards: std::iter::repeat_n("golden-egg".to_string(), 50).collect(),
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::card::CardRegistry;
    use crate::sim::playable_pool::{deckbuilder_pool, playable_pool};

    fn registry() -> CardRegistry {
        CardRegistry::load(std::path::Path::new("cards")).expect("registry loads")
    }

    /// Structural guarantee. Every preset deck must consist entirely
    /// of cards the user can actually pick (i.e. in `deckbuilder_pool`).
    /// If a preset references a card_id that doesn't exist in the
    /// pool, this test fails the build — the runtime warn-overlay
    /// in `tsot_list_preset_decks_impl` is the user-visible safety
    /// net, but the build-time test stops the corrupt preset from
    /// ever shipping.
    ///
    /// Closes the "cards in a deck are always playable" guarantee.
    #[test]
    fn every_preset_card_id_is_in_deckbuilder_pool() {
        let reg = registry();
        let pool = deckbuilder_pool(reg.cards());
        let pool_ids: std::collections::BTreeSet<&str> =
            pool.iter().map(|c| c.id.as_str()).collect();

        let presets = build_preset_decks(&pool);
        let mut violations: Vec<(String, String)> = Vec::new();
        for preset in &presets {
            for card_id in &preset.cards {
                if !pool_ids.contains(card_id.as_str()) {
                    violations.push((preset.id.clone(), card_id.clone()));
                }
            }
        }
        assert!(
            violations.is_empty(),
            "preset(s) reference card_ids not in the deckbuilder pool. \
             Either the preset is stale (delete the bad card_id) or \
             the card file is missing/malformed (fix cards/<id>.lua). \
             Violations: {violations:#?}"
        );
    }

    // ----- CardPoolEntry -----------------------------------------

    #[test]
    fn card_pool_entries_length_matches_playable_pool() {
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let entries = build_card_pool_entries(&pool);
        assert_eq!(
            entries.len(),
            pool.len(),
            "one entry per pool card, in order"
        );
    }

    #[test]
    fn card_pool_entries_carry_id_name_and_kind() {
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let entries = build_card_pool_entries(&pool);
        for (entry, card) in entries.iter().zip(pool.iter()) {
            assert_eq!(entry.id, card.id);
            assert_eq!(entry.name, card.name);
            assert_eq!(entry.kind, card.kind);
        }
    }

    #[test]
    fn card_pool_entry_cost_text_matches_format_cost() {
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let entries = build_card_pool_entries(&pool);
        for (entry, card) in entries.iter().zip(pool.iter()) {
            assert_eq!(
                entry.cost_text,
                format_cost(&card.cost),
                "card {} cost text mismatch",
                card.id
            );
        }
    }

    #[test]
    fn card_pool_entry_carries_creature_stats_only_for_creatures() {
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let entries = build_card_pool_entries(&pool);
        for (entry, card) in entries.iter().zip(pool.iter()) {
            match card.stats {
                Some(s) => {
                    assert_eq!(entry.power, Some(s.x));
                    assert_eq!(entry.toughness, Some(s.y));
                }
                None => {
                    assert!(entry.power.is_none());
                    assert!(entry.toughness.is_none());
                }
            }
        }
    }

    // ----- PresetDeck --------------------------------------------


    #[test]
    fn preset_decks_red_starter_is_50_cards_byte_for_byte() {
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let presets = build_preset_decks(&pool);
        assert_eq!(presets[0].cards.len(), 50);
        assert_eq!(
            presets[0].cards,
            RED_STARTER_DECK_IDS
                .iter()
                .map(|s| s.to_string())
                .collect::<Vec<_>>()
        );
    }

    #[test]
    fn preset_decks_blue_starter_is_50_cards_byte_for_byte() {
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let presets = build_preset_decks(&pool);
        assert_eq!(presets[1].cards.len(), 50);
        assert_eq!(
            presets[1].cards,
            STARTER_DECK_IDS
                .iter()
                .map(|s| s.to_string())
                .collect::<Vec<_>>()
        );
    }

    #[test]
    fn preset_decks_yield_test_is_50_cards_byte_for_byte() {
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let presets = build_preset_decks(&pool);
        assert_eq!(presets[2].cards.len(), 50);
        assert_eq!(
            presets[2].cards,
            YIELD_TEST_DECK_IDS
                .iter()
                .map(|s| s.to_string())
                .collect::<Vec<_>>()
        );
    }

    #[test]
    fn preset_decks_every_card_id_loads_from_registry() {
        let reg = registry();
        let by_id: std::collections::BTreeSet<&str> =
            reg.cards().iter().map(|c| c.id.as_str()).collect();
        for &id in STARTER_DECK_IDS
            .iter()
            .chain(RED_STARTER_DECK_IDS.iter())
            .chain(YIELD_TEST_DECK_IDS.iter())
        {
            assert!(
                by_id.contains(id),
                "preset references unknown card id {id:?}"
            );
        }
    }
}
