//! Per-game trace records: one JSONL line per game with everything
//! needed to reproduce it via `tsot replay`.
//!
//! Given the EA is fully deterministic from its outer `--seed`, and
//! each `game_seed` is generated by a deterministic derivation chain
//! (outer → base_seed → fitness rng → `rng.gen()` per game), a trace
//! written during a run can be `grep`d post-hoc: find the row for a
//! specific `game_seed` (as printed by `[HEARTBEAT]` / `[GAME TIMEOUT]`),
//! extract `genome` + `opponent`, feed both to `tsot replay`.
//!
//! Threading: `TraceSink` is `Send + Sync` so parallel fitness workers
//! (`sim::parallel_eval`) can share one sink. `JsonlFileTrace` guards
//! the file handle with a `Mutex`; contention is minimal since games
//! take seconds and writes are ~one per game.

use std::fs::File;
use std::io::{self, BufWriter, Write};
use std::path::Path;
use std::sync::Mutex;

use serde::{Deserialize, Serialize};

use super::AiKind;

/// Serializable mirror of [`AiKind`], minus the `Human` variant which
/// carries a non-serializable `Arc<HumanInterface>`. Traced games are
/// always AI-vs-AI (fitness / parallel eval / matchup drivers), so
/// `Human` never appears in the trace path. Attempts to convert one
/// panic — a bug in the caller, not a runtime condition.
///
/// Serde-tagged as `{"kind": "uct", "config": {...}}` so a JSONL
/// reader can dispatch on `kind` before pulling the inner config
/// out. The `Game`/`Fast`/`Stress` variants have no config and
/// serialize as `{"kind": "game"}` / `{"kind": "fast"}` / etc.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "lowercase")]
pub enum TracedAiKind {
    Game,
    Fast,
    Stress,
    Mcts { config: super::mcts::MctsConfig },
    Uct { config: super::uct::UctConfig },
}

impl TracedAiKind {
    /// Lossy conversion from `AiKind`. Panics on `AiKind::Human` —
    /// tracing a human game is a programmer error (the trace exists
    /// to replay AI-driven fitness games; humans drive their own
    /// sessions via `HumanInterface`).
    pub fn from_ai_kind(ai: &AiKind) -> Self {
        match ai {
            AiKind::Game => TracedAiKind::Game,
            AiKind::Fast => TracedAiKind::Fast,
            AiKind::Stress => TracedAiKind::Stress,
            AiKind::Mcts(cfg) => TracedAiKind::Mcts { config: cfg.clone() },
            AiKind::Uct(cfg) => TracedAiKind::Uct { config: cfg.clone() },
            AiKind::Human(_) => panic!(
                "TracedAiKind::from_ai_kind called with Human — traces are AI-only"
            ),
        }
    }

    /// Round-trip back to `AiKind`. No fallibility (every variant is
    /// safely representable in `AiKind`).
    pub fn into_ai_kind(self) -> AiKind {
        match self {
            TracedAiKind::Game => AiKind::Game,
            TracedAiKind::Fast => AiKind::Fast,
            TracedAiKind::Stress => AiKind::Stress,
            TracedAiKind::Mcts { config } => AiKind::Mcts(config),
            TracedAiKind::Uct { config } => AiKind::Uct(config),
        }
    }
}

/// One record per game. String-refs keep the hot path allocation-free —
/// serialization owns the copy.
pub struct GameTrace<'a> {
    /// The `game_seed` a `run_game_with_ai` call was invoked with.
    /// Drives all in-game RNG (draws, oracle rolls, UCT iterations).
    pub seed: u64,
    /// Shuffle seed for the side-A deck. Applied via
    /// `shuffle_units(&mut deck_a, StdRng::seed_from_u64(shuffle_seed_a))`
    /// BEFORE `GameState::from_units` — the same order the fitness eval
    /// runs. Without it, the reconstructed game's opening hand does not
    /// match the live game and every downstream turn diverges.
    pub shuffle_seed_a: u64,
    /// Shuffle seed for the side-B deck. Same contract as
    /// `shuffle_seed_a`.
    pub shuffle_seed_b: u64,
    /// The genome under evaluation as flat card ids in GENOME order
    /// (pre-shuffle). May include the `__cardless__` sentinel.
    pub genome: &'a [String],
    /// The gauntlet opponent's card ids in genome order (pre-shuffle).
    pub opponent: &'a [String],
    /// Which seat the genome played this game — `'A'` or `'B'`.
    pub seat: char,
    /// The full AI config that drove both seats. Stored as a reference
    /// so the hot path doesn't clone — serialization builds the copy.
    /// A future replay reads this back verbatim; `parse_ai(&str)`-style
    /// fallbacks with default configs are structurally impossible now.
    pub ai: &'a AiKind,
}

/// A sink for game trace records — a file, a channel, a test collector.
/// `Send + Sync` because parallel fitness workers share one sink.
pub trait TraceSink: Send + Sync {
    /// Record a single game. Must not panic; a full disk / write error
    /// should surface as an internal `eprintln!` rather than crash the
    /// EA mid-run (running EAs are expensive).
    fn record(&self, trace: GameTrace<'_>);
    /// Flush any internal buffering. Called by the CLI once the EA
    /// finishes so buffered writes are on disk before process exit.
    /// Default is no-op for sinks without buffering.
    fn flush(&self) {}
}

/// A `TraceSink` backed by a JSONL file. One `{...}\n` line per game.
///
/// Format (stable, additive-only — never rename or remove a field):
/// ```json
/// {"seed":"0x00001234abcd5678","seat":"A","ai":"game",
///  "genome":["cardA","cardB",...],
///  "opponent":["oppA","oppB",...]}
/// ```
pub struct JsonlFileTrace {
    file: Mutex<BufWriter<File>>,
}

impl JsonlFileTrace {
    /// Open `path` for writing (truncating any existing file). Returns
    /// `io::Result` — caller decides whether to propagate.
    pub fn create(path: &Path) -> io::Result<Self> {
        let f = File::create(path)?;
        Ok(Self { file: Mutex::new(BufWriter::new(f)) })
    }
}

impl TraceSink for JsonlFileTrace {
    fn flush(&self) {
        if let Err(e) = self.file.lock().unwrap().flush() {
            eprintln!("game_trace: flush failed: {e}");
        }
    }

    /// Write one JSONL line AND flush immediately. Buffering the file
    /// handle would defer disk writes indefinitely — a `tsot replay
    /// --to <token>` command run mid-EA needs to find its row NOW, not
    /// after the buffer fills or run_ea's end-of-run flush. Per-game
    /// records are ~200 bytes and there are ~15,900 per shallow run
    /// (~3 MB total); the extra syscall per record is negligible.
    fn record(&self, trace: GameTrace<'_>) {
        // Hand-serialize the primitive fields (seed, seat, genome,
        // opponent) — small strings, avoids pulling serde into the
        // primitive path. The `ai` field is a real serde payload
        // (TracedAiKind's full config) so we build that with
        // `serde_json::to_string` and splice it in.
        let ai_json = match serde_json::to_string(&TracedAiKind::from_ai_kind(trace.ai)) {
            Ok(s) => s,
            Err(e) => {
                eprintln!("game_trace: ai serialize failed: {e}");
                return;
            }
        };
        let mut line = String::with_capacity(256 + ai_json.len() + trace.genome.len() * 16);
        line.push('{');
        line.push_str(&format!("\"seed\":\"0x{:016x}\",", trace.seed));
        line.push_str(&format!("\"shuffle_seed_a\":\"0x{:016x}\",", trace.shuffle_seed_a));
        line.push_str(&format!("\"shuffle_seed_b\":\"0x{:016x}\",", trace.shuffle_seed_b));
        line.push_str(&format!("\"seat\":\"{}\",", trace.seat));
        line.push_str("\"ai\":");
        line.push_str(&ai_json);
        line.push(',');
        line.push_str("\"genome\":[");
        for (i, id) in trace.genome.iter().enumerate() {
            if i > 0 { line.push(','); }
            line.push('"');
            line.push_str(&json_escape(id));
            line.push('"');
        }
        line.push_str("],\"opponent\":[");
        for (i, id) in trace.opponent.iter().enumerate() {
            if i > 0 { line.push(','); }
            line.push('"');
            line.push_str(&json_escape(id));
            line.push('"');
        }
        line.push(']');
        line.push('}');
        line.push('\n');

        let mut f = self.file.lock().unwrap();
        if let Err(e) = f.write_all(line.as_bytes()) {
            eprintln!("game_trace: write failed: {e}");
        }
        if let Err(e) = f.flush() {
            eprintln!("game_trace: per-record flush failed: {e}");
        }
    }
}

/// Escape the JSON-string-illegal characters (`"`, `\`, control chars).
/// Card ids in this project are ASCII-safe lowercase/dashes so this is
/// defensive rather than routine.
fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Read;

    /// JsonlFileTrace writes one line per game with the seed as
    /// zero-padded 16-hex, and genome/opponent as JSON arrays. The
    /// `ai` field carries the full config, not just a kind name.
    #[test]
    fn writes_one_jsonl_line_per_record_with_expected_shape() {
        let mut p = std::env::temp_dir();
        p.push("tsot-game-trace-test.jsonl");
        let sink = JsonlFileTrace::create(&p).unwrap();

        let ai_game = AiKind::Game;
        sink.record(GameTrace {
            seed: 0xC0FFEE_1234_5678,
            shuffle_seed_a: 0x1111_2222_3333_4444,
            shuffle_seed_b: 0x5555_6666_7777_8888,
            genome: &["a".to_string(), "b".to_string(), "__cardless__".to_string()],
            opponent: &["opp1".to_string()],
            seat: 'A',
            ai: &ai_game,
        });
        let ai_fast = AiKind::Fast;
        sink.record(GameTrace {
            seed: 0xDEAD_BEEF_DEAD_BEEF,
            shuffle_seed_a: 0xAAAA_BBBB_CCCC_DDDD,
            shuffle_seed_b: 0xEEEE_FFFF_1111_2222,
            genome: &["c".to_string()],
            opponent: &["opp1".to_string(), "opp2".to_string()],
            seat: 'B',
            ai: &ai_fast,
        });
        sink.flush();
        drop(sink);

        let mut s = String::new();
        File::open(&p).unwrap().read_to_string(&mut s).unwrap();
        let lines: Vec<&str> = s.lines().collect();
        assert_eq!(lines.len(), 2, "one JSONL line per record");

        assert!(lines[0].contains("\"seed\":\"0x00c0ffee12345678\""), "line 0: {}", lines[0]);
        assert!(lines[0].contains("\"seat\":\"A\""), "line 0 seat");
        assert!(lines[0].contains("\"ai\":{\"kind\":\"game\"}"), "line 0 ai: {}", lines[0]);
        assert!(
            lines[0].contains("\"genome\":[\"a\",\"b\",\"__cardless__\"]"),
            "line 0 genome: {}",
            lines[0],
        );
        assert!(lines[0].contains("\"opponent\":[\"opp1\"]"), "line 0 opp");

        assert!(lines[1].contains("\"seed\":\"0xdeadbeefdeadbeef\""), "line 1 seed");
        assert!(lines[1].contains("\"seat\":\"B\""), "line 1 seat");
        assert!(lines[1].contains("\"ai\":{\"kind\":\"fast\"}"), "line 1 ai: {}", lines[1]);
        assert!(lines[1].contains("\"opponent\":[\"opp1\",\"opp2\"]"), "line 1 opp");

        let _ = std::fs::remove_file(&p);
    }

    /// UCT config must round-trip byte-identical through the trace's
    /// JSON serialization. This is the load-bearing invariant for
    /// exact replay of `--opponent-ai uct` games.
    #[test]
    fn uct_config_round_trips_byte_identical_through_trace_json() {
        let cfg = super::super::uct::UctConfig {
            iterations: 5,
            exploration_c: 1.41421356,
            base_seed: 0xDEAD_BEEF_CAFE_1234,
            max_candidates: 42,
            rollout_turn_cap: 3,
            per_pick_wall_ms: 12345,
        };
        let ai = AiKind::Uct(cfg.clone());
        let traced = TracedAiKind::from_ai_kind(&ai);
        let json = serde_json::to_string(&traced).unwrap();
        let decoded: TracedAiKind = serde_json::from_str(&json).unwrap();
        let round = decoded.into_ai_kind();
        match round {
            AiKind::Uct(round_cfg) => {
                assert_eq!(round_cfg.iterations, cfg.iterations);
                assert_eq!(round_cfg.exploration_c, cfg.exploration_c);
                assert_eq!(round_cfg.base_seed, cfg.base_seed);
                assert_eq!(round_cfg.max_candidates, cfg.max_candidates);
                assert_eq!(round_cfg.rollout_turn_cap, cfg.rollout_turn_cap);
                assert_eq!(round_cfg.per_pick_wall_ms, cfg.per_pick_wall_ms);
            }
            other => panic!("round trip lost the Uct variant: {other:?}"),
        }
    }

    /// MCTS config round-trip — same contract as UCT.
    #[test]
    fn mcts_config_round_trips_byte_identical_through_trace_json() {
        let cfg = super::super::mcts::MctsConfig {
            rollouts_per_candidate: 7,
            max_candidates: 13,
            base_seed: 0xFEED_FACE_1234_5678,
            max_depth: 2,
        };
        let ai = AiKind::Mcts(cfg.clone());
        let traced = TracedAiKind::from_ai_kind(&ai);
        let json = serde_json::to_string(&traced).unwrap();
        let decoded: TracedAiKind = serde_json::from_str(&json).unwrap();
        let round = decoded.into_ai_kind();
        match round {
            AiKind::Mcts(round_cfg) => {
                assert_eq!(round_cfg.rollouts_per_candidate, cfg.rollouts_per_candidate);
                assert_eq!(round_cfg.max_candidates, cfg.max_candidates);
                assert_eq!(round_cfg.base_seed, cfg.base_seed);
                assert_eq!(round_cfg.max_depth, cfg.max_depth);
            }
            other => panic!("round trip lost the Mcts variant: {other:?}"),
        }
    }

    /// JSON string-escape covers the characters that would break a
    /// JSONL consumer. Card ids are ASCII-safe so this is defensive.
    #[test]
    fn escapes_dangerous_characters() {
        assert_eq!(json_escape("plain"), "plain");
        assert_eq!(json_escape("has\"quote"), "has\\\"quote");
        assert_eq!(json_escape("back\\slash"), "back\\\\slash");
        assert_eq!(json_escape("new\nline"), "new\\nline");
    }
}
