//! Deckbuilder data: card-pool entries + preset decks.
//!
//! Two FFI-facing shapes:
//!
//! - [`CardPoolEntry`] — one entry per card the deckbuilder can offer
//!   (filtered via [`playable_pool`]). Holds the readable fields the
//!   browser UI needs: id, name, kind, cost text, colors, symbols,
//!   subtypes, ability lines, creature stats, spell timing.
//! - [`PresetDeck`] — one entry per shipped deck: the starter deck +
//!   the 7 variant-anchored gauntlet decks (Ra/Rb/Hu/Go/Uu/Pr/Gg).
//!   Each is a flat `Vec<String>` of card IDs (50 entries, with
//!   repetition) — the same shape `tsot_start_game`'s
//!   `deck_a_ids` / `deck_b_ids` consume.
//!
//! The starter deck matches what was previously hardcoded in
//! `assets/play.html::defaultStartArgs()` and what the wasm-served
//! play page boots into. Once persistence (G1) lands the user can
//! replace it with whatever they save themselves.

use crate::card::Card;
use crate::sim::fitness::{build_gauntlet, GAUNTLET_MASTER_SEED};
use crate::sim::snapshot::format_cost;
use crate::sim::variants::{variant_label, VARIANTS};

/// One card available in the deckbuilder. Shape mirrors what the JS
/// UI reads from in-game `CardView` snapshots so the renderer can be
/// shared.
#[derive(Debug, Clone, serde::Serialize)]
pub struct CardPoolEntry {
    pub id: String,
    pub name: String,
    /// `CardType` serialized as its variant name: `"Creature"` /
    /// `"Spell"` / `"Artifact"` / `"Environment"` / `"Mutation"` /
    /// `"Unspecified"`.
    pub kind: crate::card::CardType,
    /// Printed cost as a readable string: `"2H"`, `"1H+1G"`, `"0"`.
    /// Same format the in-game CardView uses, generated by
    /// [`crate::sim::snapshot::format_cost`].
    pub cost_text: String,
    pub colors: Vec<String>,
    pub symbols: Vec<String>,
    pub subtypes: Vec<String>,
    /// Creatures only. `None` for non-creature cards. Stored as
    /// `Stats.x` on the card — printed power, pre-modifiers.
    pub power: Option<f32>,
    /// Creatures only. `None` for non-creature cards. Stored as
    /// `Stats.y` on the card — printed toughness, pre-modifiers.
    pub toughness: Option<f32>,
    /// Spells only — `"Instant"` or `"Sorcery"`. `None` otherwise.
    pub timing: Option<crate::card::Timing>,
    /// Rendered ability lines (the same array `assets/play.html`
    /// shows in the card body).
    pub abilities: Vec<String>,
}

/// One shipped preset deck.
#[derive(Debug, Clone, serde::Serialize)]
pub struct PresetDeck {
    /// Stable identifier: `"starter"`, `"gauntlet-ra"`, … —
    /// used as the key in the JS preset dropdown.
    pub id: String,
    /// Display name in the preset dropdown.
    pub name: String,
    /// Flat array of card IDs with repetition; length = 50 for every
    /// shipped preset. Same shape as `tsot_start_game`'s `deck_a_ids`.
    pub cards: Vec<String>,
}

/// The current starter deck — same composition that
/// `assets/play.html` boots the deckbuilder into. Author note: this
/// list is 24+21+2+1+1+1 = 50 cards.
pub const STARTER_DECK_IDS: &[&str] = &[
    "blue-monkey", "blue-monkey", "blue-monkey", "blue-monkey",
    "blue-monkey", "blue-monkey", "blue-monkey", "blue-monkey",
    "blue-monkey", "blue-monkey", "blue-monkey", "blue-monkey",
    "blue-monkey", "blue-monkey", "blue-monkey", "blue-monkey",
    "blue-monkey", "blue-monkey", "blue-monkey", "blue-monkey",
    "blue-monkey", "blue-monkey", "blue-monkey", "blue-monkey",
    "clear-blue", "clear-blue", "clear-blue", "clear-blue", "clear-blue",
    "clear-blue", "clear-blue", "clear-blue", "clear-blue", "clear-blue",
    "clear-blue", "clear-blue", "clear-blue", "clear-blue", "clear-blue",
    "clear-blue", "clear-blue", "clear-blue", "clear-blue", "clear-blue",
    "clear-blue",
    "blue-jewel", "blue-jewel",
    "companion-bird",
    "counterspell",
    "surge",
];

/// Build `CardPoolEntry` rows from a playable-pool slice.
pub fn build_card_pool_entries(pool: &[Card]) -> Vec<CardPoolEntry> {
    pool.iter().map(card_to_entry).collect()
}

fn card_to_entry(card: &Card) -> CardPoolEntry {
    let (power, toughness) = match card.stats {
        Some(s) => (Some(s.x), Some(s.y)),
        None => (None, None),
    };
    CardPoolEntry {
        id: card.id.clone(),
        name: card.name.clone(),
        kind: card.kind,
        cost_text: format_cost(&card.cost),
        colors: card.colors.clone(),
        symbols: card.symbols.clone(),
        subtypes: card.subtypes.clone(),
        power,
        toughness,
        timing: card.timing,
        abilities: card.abilities.clone(),
    }
}

/// Build the 8 shipped presets: starter + 7 gauntlet variants.
///
/// Order is fixed so the JS preset dropdown is stable across reloads.
/// Starter is first; gauntlets follow in [`VARIANTS`] order.
pub fn build_preset_decks(playable: &[Card]) -> Vec<PresetDeck> {
    let mut out = Vec::with_capacity(1 + VARIANTS.len());
    out.push(PresetDeck {
        id: "starter".to_string(),
        name: "Starter — Blue Monkey".to_string(),
        cards: STARTER_DECK_IDS.iter().map(|s| s.to_string()).collect(),
    });
    let gauntlet = build_gauntlet(playable, GAUNTLET_MASTER_SEED);
    for (i, deck) in gauntlet.into_iter().enumerate() {
        let variant = VARIANTS[i];
        out.push(PresetDeck {
            id: format!("gauntlet-{}", variant_label(variant)),
            name: format!("Gauntlet — {}", variant_label(variant)),
            cards: deck.iter().map(|c| c.id.clone()).collect(),
        });
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::card::CardRegistry;
    use crate::sim::playable_pool::playable_pool;

    fn registry() -> CardRegistry {
        CardRegistry::load(std::path::Path::new("cards")).expect("registry loads")
    }

    // ----- CardPoolEntry -----------------------------------------

    #[test]
    fn card_pool_entries_length_matches_playable_pool() {
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let entries = build_card_pool_entries(&pool);
        assert_eq!(
            entries.len(),
            pool.len(),
            "one entry per pool card, in order"
        );
    }

    #[test]
    fn card_pool_entries_carry_id_name_and_kind() {
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let entries = build_card_pool_entries(&pool);
        for (entry, card) in entries.iter().zip(pool.iter()) {
            assert_eq!(entry.id, card.id);
            assert_eq!(entry.name, card.name);
            assert_eq!(entry.kind, card.kind);
        }
    }

    #[test]
    fn card_pool_entry_cost_text_matches_format_cost() {
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let entries = build_card_pool_entries(&pool);
        for (entry, card) in entries.iter().zip(pool.iter()) {
            assert_eq!(
                entry.cost_text,
                format_cost(&card.cost),
                "card {} cost text mismatch",
                card.id
            );
        }
    }

    #[test]
    fn card_pool_entry_carries_creature_stats_only_for_creatures() {
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let entries = build_card_pool_entries(&pool);
        for (entry, card) in entries.iter().zip(pool.iter()) {
            match card.stats {
                Some(s) => {
                    assert_eq!(entry.power, Some(s.x));
                    assert_eq!(entry.toughness, Some(s.y));
                }
                None => {
                    assert!(entry.power.is_none());
                    assert!(entry.toughness.is_none());
                }
            }
        }
    }

    // ----- PresetDeck --------------------------------------------

    #[test]
    fn preset_decks_returns_starter_plus_seven_gauntlet() {
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let presets = build_preset_decks(&pool);
        assert_eq!(presets.len(), 8, "1 starter + 7 gauntlet = 8 presets");
    }

    #[test]
    fn preset_decks_first_is_starter() {
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let presets = build_preset_decks(&pool);
        assert_eq!(presets[0].id, "starter");
        assert_eq!(presets[0].cards.len(), 50);
        assert_eq!(
            presets[0].cards,
            STARTER_DECK_IDS
                .iter()
                .map(|s| s.to_string())
                .collect::<Vec<_>>()
        );
    }

    #[test]
    fn preset_decks_gauntlet_entries_use_stable_variant_ids() {
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let presets = build_preset_decks(&pool);
        let gauntlet_ids: Vec<&str> = presets[1..]
            .iter()
            .map(|p| p.id.as_str())
            .collect();
        assert_eq!(
            gauntlet_ids,
            vec![
                "gauntlet-ra",
                "gauntlet-rb",
                "gauntlet-hu",
                "gauntlet-go",
                "gauntlet-uu",
                "gauntlet-pr",
                "gauntlet-gg",
            ]
        );
    }

    #[test]
    fn preset_decks_every_gauntlet_is_50_cards() {
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let presets = build_preset_decks(&pool);
        for p in &presets[1..] {
            assert_eq!(
                p.cards.len(),
                50,
                "gauntlet preset {} should have 50 cards",
                p.id
            );
        }
    }

    #[test]
    fn preset_decks_gauntlet_matches_build_gauntlet_byte_for_byte() {
        // The presets must use the SAME seed + builder the EA uses, so
        // a deck the human picks in the deckbuilder is identical to
        // what `fitness` evaluates against.
        let reg = registry();
        let pool = playable_pool(reg.cards());
        let presets = build_preset_decks(&pool);
        let gauntlet = build_gauntlet(&pool, GAUNTLET_MASTER_SEED);
        assert_eq!(gauntlet.len(), 7);
        for (i, deck) in gauntlet.iter().enumerate() {
            let preset = &presets[1 + i];
            let preset_ids: Vec<&str> =
                preset.cards.iter().map(|s| s.as_str()).collect();
            let gauntlet_ids: Vec<&str> =
                deck.iter().map(|c| c.id.as_str()).collect();
            assert_eq!(
                preset_ids, gauntlet_ids,
                "preset {} must equal build_gauntlet[{i}] byte-for-byte",
                preset.id
            );
        }
    }
}
