port module Main exposing (main)

{-| H7-Elm Stage 2 — port the build-info footer.

The footer is the simplest island to port: a single fixed-position div
that reads `window.__TSOT_BUILD__ = {profile, builtAt, commit}` (set
by `dist/build-info.js`, generated by the Makefile per build) and
renders one faint gray line bottom-right.

Validates the first real port wiring: js-bridge.js sends the JS
`window.__TSOT_BUILD__` value into the `buildInfoIn` port; Elm decodes
it and re-renders. Three states so the footer correctly reflects:

  - AwaitingPort     — port hasn't fired yet (initial paint)
  - NoBuildInfo      — port fired with null / decode failed
  - HasBuildInfo b   — port fired with a valid envelope

Original inline JS lived in `assets/play.html` (renderBuildFooter +
the `<div id="build-footer">` shell). Both are removed by this stage.

-}

import Browser
import Html exposing (Html, div, text)
import Html.Attributes exposing (style)
import Json.Decode as D



-- PORTS


port buildInfoIn : (D.Value -> msg) -> Sub msg



-- MODEL


type alias BuildInfo =
    { profile : String
    , builtAt : String
    , commit : String
    }


type BuildState
    = AwaitingPort
    | NoBuildInfo
    | HasBuildInfo BuildInfo


type alias Model =
    { build : BuildState
    }



-- MSG


type Msg
    = BuildInfoReceived D.Value



-- INIT


init : () -> ( Model, Cmd Msg )
init _ =
    ( { build = AwaitingPort }, Cmd.none )



-- UPDATE


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        BuildInfoReceived value ->
            case D.decodeValue decodeBuildInfo value of
                Ok info ->
                    ( { model | build = HasBuildInfo info }, Cmd.none )

                Err _ ->
                    ( { model | build = NoBuildInfo }, Cmd.none )


decodeBuildInfo : D.Decoder BuildInfo
decodeBuildInfo =
    D.map3 BuildInfo
        (D.field "profile" D.string)
        (D.field "builtAt" D.string)
        (D.field "commit" D.string)



-- SUBSCRIPTIONS


subscriptions : Model -> Sub Msg
subscriptions _ =
    buildInfoIn BuildInfoReceived



-- VIEW


view : Model -> Html Msg
view model =
    case model.build of
        AwaitingPort ->
            text ""

        NoBuildInfo ->
            footerDiv [ text "tsot · build info unavailable" ]

        HasBuildInfo info ->
            footerDiv
                [ text
                    ("tsot · "
                        ++ info.profile
                        ++ " · built "
                        ++ info.builtAt
                        ++ " · "
                        ++ info.commit
                    )
                ]


footerDiv : List (Html msg) -> Html msg
footerDiv children =
    div
        [ style "position" "fixed"
        , style "bottom" "0"
        , style "right" "0"
        , style "padding" "0.15rem 0.5rem"
        , style "background" "rgba(20,20,28,0.85)"
        , style "border-top-left-radius" "4px"
        , style "color" "#555"
        , style "font-size" "0.65rem"
        , style "font-family" "ui-monospace, SFMono-Regular, Menlo, monospace"
        , style "pointer-events" "none"
        , style "z-index" "1000"
        ]
        children



-- MAIN


main : Program () Model Msg
main =
    Browser.element
        { init = init
        , update = update
        , view = view
        , subscriptions = subscriptions
        }
